version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t app -f .circleci/Dockerfile .
      - run:
          name: Publish Docker Image
          command: |
            set -e
            docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
            case "$CIRCLE_BRANCH" in
              master) export moving_tag="prod"
                ;;
              stage) export moving_tag="beta"
                ;;
              *) export moving_tag="alpha"
                ;;
            esac
            docker tag app "jaredallard/triton-player:${moving_tag}"
            docker push "jaredallard/triton-player:${moving_tag}"

workflows:
  version: 2
  test-push:
    jobs:
      - build:
          context: Docker
          filters:
            branches:
              only:
                - master
                - stage
                - develop
